version: "2"
services:
  portal:
    depends_on:
       - mysql
       - redis
    build: ./services/portal
    # volumes:
    #   - ./services/portal:/portal
    ports:
      - "80:80"
    links:
      - mysql
      - redis
    tty: true
  redis: 
    image: redis:alpine
    ports: 
      - "6379:6379"
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./data/db/mysql:/var/lib/mysql
      - ./services/db:/docker-entrypoint-initdb.d
    environment:
       MYSQL_ROOT_PASSWORD: pass1word
       MYSQL_DATABASE: contacto_db
       MYSQL_USER: contacto
       MYSQL_PASSWORD: contacto
